<template>
  <div>
    <ux-heading level="2"
                id="api">API</ux-heading>
    <h3 class="mume-header"
        id="uxprogress">UxProgress</h3>

    <h4 class="mume-header"
        id="props">Props</h4>

    <table class="api-table">
      <thead>
        <tr>
          <th>参数名</th>
          <th>描述</th>
          <th>类型</th>
          <th>默认</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>type</td>
          <td>类型,可选值:
            <code>line</code>,
            <code>circle</code>,
            <code>dashboard</code>
          </td>
          <td>String</td>
          <td>'line'</td>
        </tr>
        <tr>
          <td>format</td>
          <td>格式化进度条内容</td>
          <td>Function(percentage)=&gt;VNode</td>
          <td></td>
        </tr>
        <tr>
          <td>status</td>
          <td>状态,可选值:
            <code>success</code>,
            <code>error</code>,
            <code>active</code>
          </td>
          <td>String</td>
          <td></td>
        </tr>
        <tr>
          <td>hide-info</td>
          <td>是否显示进度条内容</td>
          <td>Boolean</td>
          <td>false</td>
        </tr>
        <tr>
          <td>size</td>
          <td>进度条大小,可选值:
            <code>small</code>,
            <code>default</code><br>(
            <code>type=line</code>有效,
            <code>type=circle</code>请使用
            <code>width</code>设置画布大小)
          </td>
          <td>String</td>
          <td></td>
        </tr>
        <tr>
          <td>percentage</td>
          <td>百分比</td>
          <td>Number|String</td>
          <td>0</td>
        </tr>
        <tr>
          <td>stroke-width</td>
          <td>线宽</td>
          <td>Number|Sting</td>
          <td>
            <code>line</code>默认宽度为
            <code>8px</code>,
            <code>circle</code>默认值为
            <code>6px</code>
          </td>
        </tr>
        <tr>
          <td>stroke-linecap</td>
          <td>线帽,可选值:
            <code>round</code>,
            <code>square</code>
          </td>
          <td>String</td>
          <td>'round'</td>
        </tr>
        <tr>
          <td>stroke-color</td>
          <td>线条颜色</td>
          <td>String</td>
          <td></td>
        </tr>
        <tr>
          <td>width</td>
          <td>画布宽度(
            <code>type=circle</code>有效)</td>
          <td>Number|String</td>
          <td></td>
        </tr>
        <tr>
          <td>gap-degree</td>
          <td>圆形进度条缺口角度(0-360)(
            <code>type=circle</code>有效)</td>
          <td>Number|String</td>
          <td>0</td>
        </tr>
        <tr>
          <td>gap-position</td>
          <td>圆形进度条缺口位置,可选值:
            <code>top</code>,
            <code>left</code>,
            <code>right</code>,
            <code>bottom</code>(
            <code>type=circle</code>有效)</td>
          <td>String</td>
          <td>'top'</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
